org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties

minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.20)
forge_version=43.4.2
forge_version_range=[43,)
loader_version_range=[43,)
mapping_channel=official
mapping_version=1.19.2

## Mod Properties

mod_id=spartanfire
mod_name=Spartan Weaponry: Ice and Fire
mod_license=MIT License
mod_version=2.1.0
mod_issue_tracker=https://github.com/KreloX/SpartanFire/issues
mod_homepage=https://modrinth.com/mod/spartan-weaponry-ice-and-fire
mod_credits=Thanks to ChoglixVT for providing textures and to dering999 for Chinese translation. Thanks to alebentod for Russian translation.
mod_group_id=krelox.spartanfire
mod_authors=KreloX
mod_description=Addon mod for Spartan Weaponry that adds compatibility with Ice and Fire.
pack_format_number=9

# Dependency properties

spartan_weaponry_version=3.0.7
spartan_toolkit_version=1.3.0
spartan_toolkit_limit=2.0.0

ice_and_fire_version=2.1.13-1.19.2-beta-2
citadel_version=4556677